<script setup>
import { computed, useId } from 'vue'
import { taskStatusLabel, taskStatusOptions } from '../../utils/planTasks'

const props = defineProps({ task: { type: Object, required: true }, expanded: Boolean, editable: Boolean, canAsk: Boolean, pendingTask: Object, busy: Boolean, updatesBlocked: Boolean })
const emit = defineEmits(['toggle', 'update-task', 'ask-task'])
const id = useId()
const saving = computed(() => props.pendingTask?.taskId === props.task.taskId)
const statusClass = computed(() => String(props.task.status || 'UNKNOWN').toLowerCase().replaceAll('_', '-'))
const disabled = computed(() => !props.editable || props.busy || props.updatesBlocked || !props.task.taskId || !taskStatusOptions.some(option => option.value === props.task.status))
function update(status) {
  if (!disabled.value && status !== props.task.status) emit('update-task', { taskId: props.task.taskId, status })
}
</script>

<template>
  <li class="task-card" :class="[statusClass, { 'is-expanded': expanded }]" :aria-busy="saving">
    <div class="task-row">
      <button v-if="editable" class="task-check" :class="statusClass" type="button" role="checkbox" :aria-checked="task.status === 'DONE'" :aria-label="`${task.status === 'DONE' ? '重新打开' : '标记完成'}：${task.title}`" :title="task.status === 'DONE' ? '重新打开，设为待开始' : '标记完成'" :disabled="disabled" @click="update(task.status === 'DONE' ? 'TODO' : 'DONE')">
        <svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><rect class="check-box" x="4" y="4" width="16" height="16"/><path v-if="task.status === 'DONE'" class="check-stroke" d="m8 12 3 3 5-6"/><path v-else-if="task.status === 'SKIPPED'" d="M8 12h8"/><path v-else-if="task.status === 'IN_PROGRESS'" d="M8 8h8v8"/></svg>
      </button>
      <span v-else class="task-check readonly" :class="statusClass" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none"><rect class="check-box" x="4" y="4" width="16" height="16"/><path v-if="task.status === 'DONE'" d="m8 12 3 3 5-6"/></svg></span>
      <h4 class="task-heading"><button type="button" :aria-expanded="expanded" :aria-controls="id" @click="emit('toggle')"><span class="task-title">{{ task.title }}</span><span class="task-status" :class="[statusClass, { saving }]"><i aria-hidden="true"></i>{{ saving ? '保存中…' : taskStatusLabel(task.status) }}</span><svg class="task-chevron" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m6 8 4 4 4-4" /></svg></button></h4>
      <button v-if="canAsk" class="task-ask" type="button" :aria-label="`向 Agent 询问：${task.title}`" title="带到对话中，询问这项任务" :disabled="busy" @click="!busy && emit('ask-task')"><svg viewBox="0 0 22 22" fill="none" aria-hidden="true"><path d="M16 9v5a3 3 0 0 1-3 3H8l-4 3V7a3 3 0 0 1 3-3h5M16 2c.5 2 1.5 3 4 4-2.5.5-3.5 1.5-4 4-.5-2.5-1.5-3.5-4-4 2.5-1 3.5-2 4-4Z"/></svg></button>
    </div>
    <div :id="id" class="task-disclosure" :class="{ open: expanded }" :inert="!expanded" :aria-hidden="!expanded"><div class="task-disclosure-inner"><div class="task-details">
      <div v-if="task.description" class="task-description"><span>要做什么</span><p>{{ task.description }}</p></div>
      <div v-if="task.completionCriteria" class="task-criteria"><span><svg viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="m3 8 3 3 7-7"/></svg>完成标准</span><p>{{ task.completionCriteria }}</p></div>
      <p v-if="!task.description && !task.completionCriteria" class="task-empty">这项任务暂未提供详细说明。</p>
      <div v-if="editable" class="task-actions" :aria-busy="saving"><span>记录进展</span><div role="group" :aria-label="`更新任务「${task.title}」的状态`"><button v-for="option in taskStatusOptions" :key="option.value" type="button" :class="option.value.toLowerCase().replaceAll('_', '-')" :aria-pressed="task.status === option.value" :disabled="disabled || task.status === option.value" @click="update(option.value)"><i aria-hidden="true">{{ option.symbol }}</i>{{ task.status === option.value ? option.label : option.action }}</button></div><small v-if="!task.taskId">任务信息不完整，请重新读取计划。</small></div>
    </div></div></div>
  </li>
</template>

<style scoped>
.task-card { border-bottom: 1px solid var(--line); transition: background .2s; }.task-card:last-child { border-bottom: 0; }.task-row { display: flex; align-items: center; gap: 6px; }.task-card:hover { background: var(--paper); }.task-check { flex: 0 0 40px; width: 40px; height: 44px; display: grid; place-items: center; border: 0; border-radius: var(--radius-sm); padding: 8px; color: var(--ink-500); background: transparent; }.task-check svg { width: 24px; height: 24px; stroke: currentColor; stroke-width: 1.5; stroke-linecap: round; stroke-linejoin: round; }.task-check:hover:not(:disabled) { color: var(--ink-700); background: var(--canvas-soft); }.task-check.done { color: #6d9382; }.task-check.done .check-box { fill: #6d9382; stroke: #6d9382; }.task-check.done path { stroke: white; }.task-check.in-progress { color: var(--ink-500); }.task-check.skipped { color: var(--ink-500); }.task-check:disabled { opacity: .5; }.task-check.readonly { opacity: .7; }.check-stroke { animation: check-in .2s var(--ease-out); }
.task-heading { flex: 1; min-width: 0; margin: 0; font-weight: 500; }.task-heading button { width: 100%; min-height: 65px; display: grid; grid-template-columns: minmax(0, 1fr) auto 16px; align-items: center; gap: 10px; padding: 13px 10px 13px 0; border: 0; border-radius: var(--radius-sm); background: transparent; text-align: left; }.task-heading button:active { scale: 1; }.task-title { color: var(--ink); font-family: var(--text-cn); font-size: 14px; line-height: 1.75; overflow-wrap: anywhere; }.done .task-title { color: var(--ink-500); text-decoration: line-through; text-decoration-color: var(--accent-mid); }.skipped .task-title { color: var(--ink-500); }
.task-status { display: inline-flex; align-items: center; gap: 5px; font-size: 10px; font-weight: 400; color: var(--ink-500); white-space: nowrap; }.task-status i { width: 5px; height: 5px; border-radius: 50%; background: currentColor; }.task-status.done { color: #5a7f70; }.task-status.in-progress { color: var(--ink-500); }.task-status.skipped { color: #927783; }.task-chevron { width: 16px; height: 16px; stroke: var(--line-strong); stroke-width: 1.5; transition: transform .25s; }.is-expanded .task-chevron { transform: rotate(180deg); }
.task-disclosure { display: grid; grid-template-rows: 0fr; opacity: 0; transition: grid-template-rows .25s var(--ease-out), opacity .2s; }.task-disclosure.open { grid-template-rows: 1fr; opacity: 1; }.task-disclosure-inner { overflow: hidden; min-height: 0; }.task-details { padding: 0 14px 18px 46px; display: grid; gap: 13px; }.task-details > div > span { color: var(--ink-500); font-size: 11px; font-weight: 500; }.task-details p { margin: 6px 0 0; color: var(--ink-700); font-size: 13px; line-height: 1.9; white-space: pre-line; overflow-wrap: anywhere; }
.task-criteria { padding: 11px 14px; background: #f0f5f2; border-radius: var(--radius-sm); }.task-criteria > span { display: flex; align-items: center; gap: 5px; color: #587567 !important; }.task-criteria svg { width: 14px; height: 14px; stroke: currentColor; stroke-width: 1.5; }.task-criteria p { color: #586c61; }
.task-actions { display: flex; flex-wrap: wrap; align-items: center; gap: 9px; }.task-actions > div { display: flex; flex-wrap: wrap; gap: 6px; }.task-actions button { display: inline-flex; align-items: center; justify-content: center; gap: 5px; min-height: 34px; padding: 6px 10px; border: 0; border-radius: var(--radius-sm); color: var(--ink-500); background: var(--canvas-soft); font-size: 11px; }.task-actions i { font-style: normal; font-size: 14px; }.task-actions button.done { color: #5c7d6f; background: #eaf2ed; }.task-actions button.skipped { color: var(--ink-500); background: var(--canvas-soft); }.task-actions button:disabled { opacity: .5; }.task-actions button[aria-pressed="true"] { color: white; background: var(--accent); opacity: 1; }.task-actions button.done[aria-pressed="true"] { background: #497359; }.task-actions small { width: 100%; font-size: 11px; color: var(--ink-500); }.task-empty { color: var(--ink-500); font-size: 12px; }
.task-status.saving i { width: 9px; height: 9px; border: 1.5px solid var(--line); border-top-color: var(--accent); background: transparent; animation: task-saving .7s linear infinite; }@keyframes task-saving { to { transform: rotate(360deg); } }@keyframes check-in { from { opacity: 0; transform: scale(.7); transform-origin: center; } }
.task-ask { flex: 0 0 30px; height: 32px; padding: 6px; border: 0; border-radius: var(--radius-sm); background: transparent; color: var(--ink-500); opacity: .7; }.task-ask svg { width: 19px; height: 19px; stroke: currentColor; stroke-width: 1.2; stroke-linecap: round; stroke-linejoin: round; }.task-row:hover .task-ask, .task-row:focus-within .task-ask { opacity: 1; color: var(--ink-500); background: var(--canvas-soft); }.task-ask:hover:not(:disabled) { transform: translateY(-1px); background: var(--accent-soft); }.task-ask:disabled { opacity: .3; }.task-card.is-expanded { background: linear-gradient(110deg, var(--paper), var(--paper)); }.task-card { border-bottom-color: color-mix(in srgb, var(--line) 50%, transparent); }.task-check:hover:not(:disabled) svg { transform: scale(1.09); }.task-check svg { transition: transform .18s var(--ease-out); }
.task-ask { color: #567664; opacity: .85; }.task-row:hover .task-ask, .task-row:focus-within .task-ask { color: var(--accent-deep); background: #e6efdd; }.task-card.is-expanded { background: #f2f7ed; }.task-check.done { color: #497359; }.task-check.done .check-box { fill: #497359; stroke: #497359; }.check-stroke { stroke-dasharray: 14; animation: check-in .25s var(--ease-out); }
@keyframes check-in { from { stroke-dashoffset: 14; opacity: .3; } to { stroke-dashoffset: 0; opacity: 1; } }
@container stage (max-width: 480px) { .task-heading button { grid-template-columns: minmax(0, 1fr) 16px; gap: 2px 8px; padding-block: 12px; }.task-title { font-size: 13px; }.task-status { grid-row: 2; grid-column: 1; }.task-chevron { grid-row: 1 / 3; grid-column: 2; }.task-details { padding: 0 5px 16px 8px; }.task-details p { font-size: 12px; }.task-actions > div { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); width: 100%; }.task-actions button { min-height: 38px; } }
</style>
